### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by abhijeetsingh1704** [dridk/abif#1]
**Installation**

Is this s general issue of something wrong with my system? Can this be fixed?

`make`

g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o main.cpp
main.cpp:5:10: **fatal error: QtCore: No such file or directory**
 #include **\<QtCore>**
...............**^~~~~~~~**
compilation terminated.
Makefile:352: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by dridk** [comment]
yes, you should install Qt5 library. 
But don't use this tool. I will remove it. 
Go and use tracy instead
 https://github.com/gear-genomics/tracy

You can also try my CutePeaks 
https://github.com/labsquare/CutePeaks

**Comment by dridk** [comment]
I miss to remove QtCore from dependency.. It is not required ! I will fix it

**Comment by abhijeetsingh1704** [comment]
Thanks @dridk 
Sounds nice.
However, just wanted to confirm, as it appears, tracy and CutePeaks are not doing the same as abif is supposed to do (.fsa files), or?

**Comment by dridk** [comment]
.fsa file is the same format than abif format. 
You should be able to read fsa data with any abif library.

**Comment by dridk** [comment]
Hi ! I just fixed some issue ! 
You should be able to compile this using the new makefile. 
Note that libtclap-dev is required . 

Let met know if it works for you
